name: Deploy app to server

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clear Docker cache
        run: docker system prune --all --force --volumes
      - name: Clear cache
        run: sudo rm -rf /opt/hostedtoolcache
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/airbnb-images:latest
          no-cache: true  # Tambahkan ini untuk menghindari cache

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop airbnb || true
            docker rm airbnb || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/airbnb-images:latest || true
            docker images -q --filter "dangling=true" | xargs -r docker rmi || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/airbnb-images:latest
            docker run -d -p 80:8080 \
              -e DBUSER=${{ secrets.DBUSER }} \
              -e DBPASS=${{ secrets.DBPASS }} \
              -e DBHOST=${{ secrets.DBHOST }} \
              -e DBPORT=${{ secrets.DBPORT }} \
              -e DBNAME=${{ secrets.DBNAME }} \
              -e S3BUCKETNAME=${{ secrets.S3BUCKETNAME }} \
              -e S3REGION=${{ secrets.S3REGION }} \
              -e S3ACCESKEY=${{ secrets.S3ACCESKEY }} \
              -e S3SECRETACCESKEY=${{ secrets.S3SECRETACCESKEY }} \
              --name airbnb ${{ secrets.DOCKERHUB_USERNAME }}/airbnb-images:latest

